# Generated by Django 5.2.3 on 2025-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gambar',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
