# Generated by Django 5.2.3 on 2025-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Ceritakan sedikit tentang diri Anda.', max_length=500),
        ),
    ]
