# Generated by Django 5.2.3 on 2025-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorit',
            field=models.ManyToManyField(blank=True, related_name='difavoritkan_oleh', to='catalog.game'),
        ),
    ]
