# Generated by Django 5.2.3 on 2025-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_profile_favorit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
